
name: Node project group 2

run-name: ${{ github.actor }} Workflow group 2

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm install
      
      - name: Test app
        run: npm test
      
      - name: Start App
        run: npm start &
      
      - name: Get output
        run: wget localhost:3000/api/latest-releases -O latest-releases.json

      - name: Publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: Latest releases artifact
          path: latest-releases.json

