name: Node project group 2 - When a specific folder have been modified
  
run-name: ${{ github.actor }} pushed on dev
on:
  pull_request:
    types: [opened, closed]
jobs:
  pr-opened:
    if: github.event.action == 'opened'
    uses: ./.github/workflows/reusable_workflow.yml
  
  pr-closed:
    if: github.event.action == 'closed'
    uses: ./.github/workflows/reusable_workflow.yml
    
