name: Node project group 2 - When you have a push on any branch where the name starts with "feat"
  
run-name: ${{ github.actor }} pushed on dev
on: 
  push:
    branches:    
      - 'feat/*'       # matches every branch containing a single '/'
jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable_workflow.yml

