
name: Node project group 2 - task 1.2
  
run-name: ${{ github.actor }} pushed on dev
on: 
  push:
    branches:
      - 'dev'
jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable_workflow.yml

