name: Node project group 2 - When only the files with a .js extension have been modified
  
run-name: ${{ github.actor }} pushed on dev
on: 
  push:
    paths:
      - '**.js'
jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable_workflow.yml

