
name: Node project group 2

on: 
  push:
    branches:
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm install
      - name: Test app
        run: npm test
      - name: Start App
        run: npm start &
      - name: Get output
        run: wget localhost:3000/api/latest-releases -O latest-releases.json
    steps:
      - uses: actions/upload-artifact@v4
        with:
          name: Latest releases artifact
          path: latest-releases.json

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Execute tests
        run: exit 0
  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Deploy app
        run: exit 0


Create and publish 3 branches, "dev", "staging", "feat/feature-1"
When you have a push on the branch "dev" only
When you have a push on any branch except "staging"
When you have a push on any branch where the name starts with "feat"
When only the files with a .js extension have been modified
When a specific folder have been modified

